/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaDeCambio.java
 *
 * Created on 09-jun-2012, 12:05:55
 */

package practica1;

import javax.security.auth.login.Configuration;

/**
 *
 * @author PATRICIO
 */
public class VentanaDeCambio extends javax.swing.JFrame {

    /** Creates new form VentanaDeCambio */
    public VentanaDeCambio() {
        initComponents();
        txtEjecucion.setEditable(false);
        txtEvolucion.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIngreseValor = new javax.swing.JLabel();
        txtMonto = new javax.swing.JFormattedTextField();
        btnObtenerCambio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAResultado = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        lblTEvolucion = new javax.swing.JLabel();
        txtEvolucion = new javax.swing.JTextField();
        lblEjecucion = new javax.swing.JLabel();
        txtEjecucion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("PROGRAMA DE CAMBIO EN MONEDAS");

        lblIngreseValor.setText("Ingrese Valor");

        txtMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnObtenerCambio.setText("Obtener Cambio");
        btnObtenerCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerCambioActionPerformed(evt);
            }
        });

        txtAResultado.setColumns(20);
        txtAResultado.setRows(5);
        jScrollPane2.setViewportView(txtAResultado);

        btnLimpiar.setText("Intentar otro valor");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblTEvolucion.setText("Tiempo de Evolución: ms");

        lblEjecucion.setText("Tiempo de Ejecución en milisegundos");

        txtEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEjecucionActionPerformed(evt);
            }
        });

        jLabel1.setText("UPeU-Juliaca(FINANZAS)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblIngreseValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObtenerCambio)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEjecucion)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTEvolucion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEvolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIngreseValor)
                    .addComponent(btnObtenerCambio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(lblTEvolucion)
                    .addComponent(txtEvolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEjecucion)
                    .addComponent(txtEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerCambioActionPerformed
        this.valor=0;
        if(txtMonto.getText().equals("")){
            valor=0;
        }else{
            //this.valor=Integer.parseInt(txtMonto.getText());
        try {
            if(txtMonto.getText().isEmpty()){
                
            }
            this.valor=Integer.parseInt(txtMonto.getText());
            CambioMinimo.calcularCambioMinimo(valor);
            txtAResultado.setText(CambioMinimo.obtenerResultado());

        } catch (Exception e) {
            System.out.println("Error valor mal ingresado"+ e);
            valor=0;
        }
        txtEvolucion.setText(String.valueOf(CambioMinimo.obtenerTiempoEvolucion()));
        txtEjecucion.setText(String.valueOf(System.currentTimeMillis()));
        txtMonto.setEditable(false);
//        txtEjecucion.setEditable(false);
//        txtEvolucion.setEditable(false);
        txtAResultado.setEditable(false);
        }
//        //this.valor=Integer.parseInt(txtMonto.getText());
//        try {
//            this.valor=Integer.parseInt(txtMonto.getText());
//            CambioMinimo.calcularCambioMinimo(valor);
//            txtAResultado.setText(CambioMinimo.obtenerResultado());
//
//        } catch (Exception e) {
//            System.out.println("Error valor mal ingresado"+ e);
//            txtMonto.setEditable(true);
//            txtAResultado.setEditable(true);
//        }
//        txtMonto.setEditable(false);
//        txtAResultado.setEditable(false);
    }//GEN-LAST:event_btnObtenerCambioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.txtAResultado.setText("");
        this.txtMonto.setText("");
        this.txtEjecucion.setText("");
        this.txtEvolucion.setText("");
        this.txtAResultado.setEditable(true);
        this.txtMonto.setEditable(true);
//        txtEjecucion.setEditable(true);
//        txtEvolucion.setEditable(true);
        
        //initComponents();
        Configuration.getConfiguration().refresh();
        this.valor=0;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEjecucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEjecucionActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDeCambio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnObtenerCambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEjecucion;
    private javax.swing.JLabel lblIngreseValor;
    private javax.swing.JLabel lblTEvolucion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAResultado;
    private javax.swing.JTextField txtEjecucion;
    private javax.swing.JTextField txtEvolucion;
    private javax.swing.JFormattedTextField txtMonto;
    // End of variables declaration//GEN-END:variables
    private int valor=0;
    CambioMinimo cm=new CambioMinimo();
}
